### ISSUE TITLE
Проверка дорешек

### ISSUE THREAD

**Issue by nzinov** [dainiak/tpbeta#2]
Когда дорешка проверена, то письмо на почту не приходит, как раньше (с ручным управлением) это было, а хотелось бы. В коде я ничего на этот счет не вижу - вы еще не зафиксировали эти изменения со статусами дорешек?

**Comment by dainiak** [comment]
Теперь зафиксировал. Запилите отсылку электронных писем?

**Comment by nzinov** [comment]
Сделал #3
